# Generated by Django 3.1.7 on 2021-04-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
    ]
